export const mealNameInput = '[e2e-data="meal-name"]'
export const mealErrorText = '[e2e-data="error-valid-name"]'
export const mealDescriptionInput = '[e2e-data="meal-description"]'
export const mealPriceInput = '[e2e-data="meal-price"]'
export const mealPriceErrorText = '[e2e-data="error-valid-price"]'
export const addMealButton = '[e2e-data="add-meal"]'
export const mealItems = '[e2e-data*="meal-items"]'
export const mealItemName = '[e2e-data="meal-item-name"]'
export const mealItemDescription = '[e2e-data="meal-item-description"]'
export const mealItemPrice = '[e2e-data="meal-item-price"]'
export const mealItem = (mealName = '', inputId = '') => `[e2e-data*="meal-items-${mealName.replaceAll(' ', '-')}"] ${inputId}`
export const amountInput = '[e2e-data="amount-input"]'
export const addToCart = '[e2e-data="add-to-cart"]'
export const cartButton = '[e2e-data="cart-icon-number"]'
export const cartItems = (mealName = '', type = '') => `[e2e-data*="cart-items-${mealName.replaceAll(' ', '-')}"] ${type}`
export const cartItemName = '[e2e-data="cart-item-name"]'
export const cartItemPrice = '[e2e-data="cart-item-price"]'
export const cartItemAmount = '[e2e-data="cart-item-amount"]'
export const totalAmount = '[e2e-data="total-amount"]'
export const orderButton = '[e2e-data="order-button"]'
export const removeItemFromCart = '[e2e-data="remove-item"]'
export const addItemToCart = '[e2e-data="add-item"]'
