name: "Sanity"
on:
  pull_request
jobs:
  runTests:
    name: Cypress run
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm i
        timeout-minutes: 5
      - name: build packages
        run: npm run build
        timeout-minutes: 2
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          # we have already installed all dependencies above
          install: false
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 3
