name: "Sanity"
on:
  pull_request
jobs:
  runTests:
    name: Cypress run
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: npm i
        timeout-minutes: 5
      - name: build packages
        run: npm run build
        timeout-minutes: 2
      - name: start project
        run: npm start
        timeout-minutes: 2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
